steps:
- id: 'Build and store images'
  name: 'gcr.io/k8s-skaffold/skaffold:latest'
  entrypoint: 'bash'
  args: 
  - '-c'
  - > 
    gsutil cp gs://hipstershop-cache/cache ../root/cache && skaffold build --cache-artifacts --cache-file=../root/cache --default-repo=gcr.io/hipstershop-264010 && gsutil cp ../root/cache gs://hipstershop-cache/cache;
timeout: '3600s'
options:
  machineType: 'N1_HIGHCPU_32'