version: 2.1
jobs:
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run: |
          echo $GCP_PROJECT_KEY | base64 --decode > ${HOME}/gcloud-service-key.json
          gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json --project $GOOGLE_PROJECT_ID
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          gcloud container clusters get-credentials $CLUSTER_NAME
          gcloud builds submit --config=cloudbuild.yaml
          kubectl set image deployments/frontend server=gcr.io/hipstershop-264010/frontend:latest
          kubectl set image deployments/adservice server=gcr.io/hipstershop-264010/adservice:latest
          kubectl set image deployments/cartservice server=gcr.io/hipstershop-264010/cartservice:latest
          kubectl set image deployments/checkoutservice server=gcr.io/hipstershop-264010/checkoutservice:latest
          kubectl set image deployments/currencyservice server=gcr.io/hipstershop-264010/currencyservice:latest
          kubectl set image deployments/emailservice server=gcr.io/hipstershop-264010/emailservice:latest
          kubectl set image deployments/loadgenerator main=gcr.io/hipstershop-264010/loadgenerator:latest
          kubectl set image deployments/paymentservice server=gcr.io/hipstershop-264010/paymentservice:latest
          kubectl set image deployments/productcatalogservice server=gcr.io/hipstershop-264010/productcatalogservice:latest
          kubectl set image deployments/recommendationservice server=gcr.io/hipstershop-264010/recommendationservice:latest
          kubectl set image deployments/redis-cart redis=gcr.io/hipstershop-264010/redis-cart:latest
          kubectl set image deployments/shippingservice server=gcr.io/hipstershop-264010/shippingservice:latest
workflows:
  version: 2.1
  main:
    jobs:
      - deploy



          # kubectl create secret docker-registry gcr-access-token --docker-server=gcr.io --docker-username=oauth3accesstoken --docker-password="$(gcloud auth print-access-token)" --docker-email=any@valid.email
          # kubectl patch serviceaccount default -p '{"imagePullSecrets": [{"name": "gcr-access-token"}]}'
      # kubectl set image deployments/kubernetes-bootcamp kubernetes-bootcamp=jocatalin/kubernetes-bootcamp:v2
# kubectl create secret docker-registry gcr-json-key --docker-server=gcr.io --docker-username=_json_key --docker-password="$(cat ../../../Desktop/hs.json)" --docker-email=any@valid.email
# kubectl patch serviceaccount default -p '{"imagePullSecrets": [{"name": "gcr-json-key"}]}'