version: 2.1
jobs:
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      # executes tests for ratingservice
      - run: cd src/ratingservice/ && npm install && npm test && cd ../../
      # creates api key json file from base64 encoded env
      - run: echo $GCP_PROJECT_KEY | base64 --decode > ${HOME}/gcloud-service-key.json
      # authenticates at GCP
      - run: gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json --project $GOOGLE_PROJECT_ID
      - run: gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run: gcloud container clusters get-credentials $CLUSTER_NAME
      # submit build job to google cloud build
      - run: gcloud builds submit --config=cloudbuild.yaml
      # generates new release artifacts
      - run: TAG=latest REPO_PREFIX=gcr.io/hipstershop-264010 ./hack/make-release-artifacts.sh
      # Triggers Kubernetes to check for new releases and deploy these
      - run: kubectl apply -f release/kubernetes-manifests.yaml
workflows:
  version: 2.1
  main:
    jobs:
      - deploy